DROP TABLE IF EXISTS "comment_votes";
DROP TABLE IF EXISTS "post_votes";
DROP TABLE IF EXISTS "post_images";
DROP TABLE IF EXISTS "comments";
DROP TABLE IF EXISTS "posts";
DROP TABLE IF EXISTS "subleddits";
DROP TABLE IF EXISTS "users";
DROP TYPE IF EXISTS "vote_type";
DROP TYPE IF EXISTS "user_role";