// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: subleddits.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSubleddit = `-- name: CreateSubleddit :one
INSERT INTO "subleddits" (
    name,
    user_id
) VALUES (
    $1, $2
) RETURNING id, name, user_id, created_at, updated_at
`

type CreateSubledditParams struct {
	Name   string        `json:"name"`
	UserID uuid.NullUUID `json:"user_id"`
}

func (q *Queries) CreateSubleddit(ctx context.Context, arg CreateSubledditParams) (Subleddit, error) {
	row := q.db.QueryRowContext(ctx, createSubleddit, arg.Name, arg.UserID)
	var i Subleddit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubleddit = `-- name: DeleteSubleddit :exec
DELETE FROM "subleddits"
WHERE name = $1
`

func (q *Queries) DeleteSubleddit(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteSubleddit, name)
	return err
}
